export function getCoinCategories(): string[] {
    return [
        "Cryptocurrency",
        "Smart Contract Platform",
        "Near Protocol Ecosystem",
        "Fantom Ecosystem",
        "Arbitrum Ecosystem",
        "Avalanche Ecosystem",
        "Binance Smart Chain Ecosystem",
        "Polygon Ecosystem",
        "USD Stablecoin",
        "Stablecoins",
        "Centralized Exchange Token (CEX)",
        "Exchange-based Tokens",
        "xDAI Ecosystem",
        "Solana Ecosystem",
        "Cosmos Ecosystem",
        "Terra Ecosystem",
        "Decentralized Finance (DeFi)",
        "Polkadot Ecosystem",
        "Meme Tokens",
        "Harmony Ecosystem",
        "Seigniorage",
        "Wrapped-Tokens",
        "Tokenized BTC",
        "Eth 2.0 Staking",
        "Infrastructure",
        "Oracle",
        "Business Services",
        "Automated Market Maker (AMM)",
        "Governance",
        "Decentralized Exchange Token (DEX)",
        "Yield Farming",
        "Internet of Things (IOT)",
        "Artificial Intelligence",
        "Business Platform",
        "Axie Infinity",
        "Metaverse",
        "Play To Earn",
        "Non-Fungible Tokens (NFT)",
        "Gaming",
        "Storage",
        "Protocol",
        "Privacy Coins",
        "Entertainment",
        "Finance / Banking",
        "Compound Tokens",
        "Asset-backed Tokens",
        "Analytics",
        "Without category",
        "Lending/Borrowing",
        "Sports",
        "Communication",
        "Yield Aggregator",
        "Celo Ecosystem",
        "Olympus Pro",
        "Synthetic Issuer",
        "Derivatives",
        "Masternodes",
        "Music",
        "Yearn Ecosystem",
        "Insurance",
        "MEV Protection",
        "Prediction Markets",
        "Collectibles",
        "Number",
        "Technology & Science",
        "Tokenized Gold",
        "Perpetuals",
        "Social Money",
        "Rebase Tokens",
        "Wallets",
        "Asset Manager",
        "Launchpad",
        "Investment",
        "ETF",
        "Options",
        "Software",
        "DaoMaker Ecosystem",
        "Energy",
        "HECO Chain Ecosystem",
        "Binance Launchpool",
        "EUR Stablecoin",
        "Synths",
        "Big Data",
        "Gambling",
        "Media",
        "Index",
        "DeFi Index",
        "Structured Products",
        "TokenSets",
        "Leveraged Token",
        "Tourism",
        "Real Estate",
        "Augmented Reality",
        "Virtual Reality",
        "Marketing",
        "Fan Token"
    ];
}