_ts_file_basic_start = '''/*Auto generated by script - direct changes will be overwritten soon*/
'''

ts_file_coin_lookup_start = _ts_file_basic_start + '''
import {LookupAssetInfo} from '../../../interfaces-asset';
export const lookupCoinInfo: LookupAssetInfo<'coin'> = {
'''

ts_file_exchange_lookup_start = _ts_file_basic_start + '''
import {ExchangeInfo} from '../interfaces';
export const lookupCoinExchangeInfo: {[exchange in string]: ExchangeInfo<'coin'>} = {
'''

ts_file_end = '''\n};'''