interface IconMap {
    add: string;
    menu: string;
    back: string;
    options: string;
    search: string;
    delete: string;
    modify: string;
    price: string;
    market: string;
    change: string;
    update: string;
    savings: string;
    supply: string;
    views: string;
    portfolio: string;
    test: string;
    tutorial: string;
    share: string;
    proVersion: string;
    settings: string;
    notes: string;
    clear: string;
    commitChange: string;
    copy: string;
    restoreDefault: string;
    info: string;
    functions: string;
    metrics: string;
    faq: string;
    other: string;
    login: string;
    logout: string;
    policy: string;
    warn: string;
    questionMark: string;
    lightBulb: string;
    pin: string;
    refresh: string;
    error: string;
    remove: string;
    groups: string;
}


export const materialIcons: Readonly<IconMap> = {
    add: 'add',
    menu: 'menu',
    back: 'arrow_back',
    options: 'more_vert',
    search: 'search',
    delete: 'delete',
    modify: 'tune',
    price: 'trending_up',
    market: 'table_chart',
    change: 'change_history',
    supply: 'pie_chart',
    views: 'query_stats',
    portfolio: 'donut_large',
    test: 'science',
    update: 'update',
    savings: 'savings',
    tutorial: 'school',
    share: 'share',
    proVersion: 'star_outline',
    settings: 'settings',
    notes: 'list_alt',
    clear: 'clear',
    commitChange: 'check',
    copy: 'content_copy',
    restoreDefault: 'settings_backup_restore',
    info: 'info_outlined',
    functions: 'functions',
    metrics: 'local_offer',
    other: 'more',
    faq: 'question_answer',
    login: 'login',
    logout: 'logout',
    policy: 'policy',
    warn: 'warning',
    questionMark: 'help_outline',
    lightBulb: 'emoji_objects',
    pin: 'push_pin',
    refresh: 'refresh',
    error: 'local_fire_department',
    remove: 'remove',
    groups: 'groups'
};
